# Generated by Django 4.2.10 on 2024-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=225)),
                ('business_title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('website', models.URLField(max_length=225)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
