# Generated by Django 4.2.10 on 2024-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='business_title',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='website',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
